export const filmes = [
    {
        titulo:'Harry Potter',
        genero:'Fantasia',
        stars:5,
        descriçao:'Harry Potter é um garoto órfão que vive infeliz com seus tios, os Dursleys. Ele recebe uma carta contendo um convite para ingressar em Hogwarts, uma famosa escola especializada em formar jovens bruxos. Inicialmente, Harry é impedido de ler a carta por seu tio, mas logo recebe a visita de Hagrid, o guarda-caça de Hogwarts, que chega para levá-lo até a escola. Harry adentra um mundo mágico que jamais imaginara, vivendo diversas aventuras com seus novos amigos, Rony Weasley e Hermione Granger.',
        img:'https://upload.wikimedia.org/wikipedia/pt/3/33/Chamber_of_Secrets.jpg',
        assistir:'https://google.com',
    },
    {
        titulo:'Infiltrados',
        genero:'Açao',
        stars:5,
        descriçao:'Filme muito bom pra matar o tédio',
        img:'https://capas-p.imagemfilmes.com.br/164908_000_p.jpg',
        assistir:'https://google.com',
    },
    {
        titulo:'Encare a música',
        genero:'Musical',
        stars:5,
        descriçao:'Filme pra viadinho',
        img:'https://capas-p.imagemfilmes.com.br/164909_000_p.jpg',
        assistir:'https://google.com',
    },
    {
        titulo:'Eu Acredito',
        genero:'Superação',
        stars:5,
        descriçao:'Filme para refletir',
        img:'https://capas-p.imagemfilmes.com.br/164847_000_p.jpg',
        assistir:'https://capas-p.imagemfilmes.com.br/164847_000_p.jpg',
    },
    {
        titulo:'A Cabana',
        genero:'Suspense',
        stars:5,
        descriçao:'Filme pra cagar de medo',
        img:'https://lojasaraiva.vteximg.com.br/arquivos/ids/12109083/1006637057.jpg?v=637142248087230000',
        assistir:'https://lojasaraiva.vteximg.com.br/arquivos/ids/12109083/1006637057.jpg?v=637142248087230000',
    },
    {
        titulo:'Subirbor',
        genero:'Nao Sei',
        stars:5,
        descriçao:'Filme top para se ver a primeira vez',
        img:'https://capas-p.imagemfilmes.com.br/164859_000_p.jpg',
        assistir:'https://capas-p.imagemfilmes.com.br/164859_000_p.jpg',
    },
    {
        titulo:'Mulan',
        genero:'Infantil',
        stars:5,
        descriçao:'Muito bom para se ver com a familia',
        img:'https://images-na.ssl-images-amazon.com/images/I/91++nYXJ5dL.jpg',
        assistir:'https://images-na.ssl-images-amazon.com/images/I/91++nYXJ5dL.jpg',
    },

]